#Creación de *DataFrames*

Una DataFrame es el formato estructurado para gestión de los datos en `Python`.

La librería que gestiona este tipo de estructuras se llama `Pandas`.

In [ ]:
# Primero cargamos las librerías que necesitamos
# para el desarrollo del código

import pandas as pd #gestiona los DataFrames

In [ ]:
# Segundo, creamos una lista con la información
# de los estudiantes

estudiantes = [['Mónica', 'Bejarano', 'Contaduría', 16],
               ['Lina', 'Sepúlveda', 'Electrónica', 42],
               ['Maria Camila', 'Rivillas', 'Contaduría', 17],
               ['Laura Sofía', 'Guzman', 'Contaduría', 16],
               ['Sofía', 'Pérez', 'Contaduría', 16],
               ['Juliana', 'Carvajal', 'Contaduría', 17],
               ['Miguel Ángel', 'Monroy', 'Contaduría', 17],
               ['Sara Isabel', 'Bermúdez', 'Contaduría', 19],
               ['Sara Valentina', 'Pulido', 'Contaduría', 18],
               ['Paulina', 'Bedoya', 'Contaduría', 17],
               ['Sury', 'Salazar', 'Contaduría', 17],
               ['Samuel', 'Tamayo', 'Contaduría', 17],
               ['Paulina', 'Chavarriaga', 'Contaduría', 17],
               ['Salome', 'Mora', 'Contaduría', 19],
               ['Santiago', 'Perdomo', 'Administración', 22],
               ['Juan José', 'Giraldo', 'Administración', 24]]

In [ ]:
# Una vez construida la lista, podemos proceder a crear el DataFrame

df_estudiantes = pd.DataFrame(estudiantes)

# Visualizamos para comprobar
df_estudiantes

In [ ]:
# Para ponerle nombre a las columnas procedemos así:
df_estudiantes.columns = ['Nombre', 'Apellido', 'Carrera', 'Edad']

# Visualizamos para comprobar. En este caso solo visualizaremos
# los primeros 5 estudiantes
df_estudiantes.head(5)

In [ ]:

# Para seleccionar una sola columna, podemos hacerlo de dos maneras

# Forma 1
df_estudiantes['Carrera']

In [ ]:
# Forma 2
df_estudiantes.Carrera

0         Contaduría
1        Electrónica
2         Contaduría
3         Contaduría
4         Contaduría
5         Contaduría
6         Contaduría
7         Contaduría
8         Contaduría
9         Contaduría
10        Contaduría
11        Contaduría
12        Contaduría
13        Contaduría
14    Administración
15    Administración
Name: Carrera, dtype: object

In [ ]:
# Supongamos que queremos seleccionar dos columnas: Nombre, Apellido
df_estudiantes[['Nombre', 'Apellido']]

            Nombre     Apellido
0           Mónica     Bejarano
1             Lina    Sepúlveda
2     Maria Camila     Rivillas
3      Laura Sofía       Guzman
4            Sofía        Pérez
5          Juliana     Carvajal
6     Miguel Ángel       Monroy
7      Sara Isabel     Bermúdez
8   Sara Valentina       Pulido
9          Paulina       Bedoya
10            Sury      Salazar
11          Samuel       Tamayo
12         Paulina  Chavarriaga
13          Salome         Mora
14        Santiago      Perdomo
15       Juan José      Giraldo

In [ ]:
# ¿Cómo podríamos crear una nueva columna llamada "Nombre completo" con la
# unión del Nombre y el Apellido?

df_estudiantes['Nombre completo'] = df_estudiantes['Nombre'] + ' ' + df_estudiantes['Apellido']
df_estudiantes

            Nombre     Apellido         Carrera  Edad        Nombre completo
0           Mónica     Bejarano      Contaduría    16        Mónica Bejarano
1             Lina    Sepúlveda     Electrónica    42         Lina Sepúlveda
2     Maria Camila     Rivillas      Contaduría    17  Maria Camila Rivillas
3      Laura Sofía       Guzman      Contaduría    16     Laura Sofía Guzman
4            Sofía        Pérez      Contaduría    16            Sofía Pérez
5          Juliana     Carvajal      Contaduría    17       Juliana Carvajal
6     Miguel Ángel       Monroy      Contaduría    17    Miguel Ángel Monroy
7      Sara Isabel     Bermúdez      Contaduría    19   Sara Isabel Bermúdez
8   Sara Valentina       Pulido      Contaduría    18  Sara Valentina Pulido
9          Paulina       Bedoya      Contaduría    17         Paulina Bedoya
10            Sury      Salazar      Contaduría    17           Sury Salazar
11          Samuel       Tamayo      Contaduría    17          Samuel Tamayo
12         Paulina  Chavarriaga      Contaduría    17    Paulina Chavarriaga
13          Salome         Mora      Contaduría    19            Salome Mora
14        Santiago      Perdomo  Administración    22       Santiago Perdomo
15       Juan José      Giraldo  Administración    24      Juan José Giraldo

In [ ]:
# Ahora, vamos a remover una fila de la tabla

df_estudiantes = df_estudiantes.drop(1)

df_estudiantes.tail(5)

       Nombre     Apellido         Carrera  Edad      Nombre completo
11     Samuel       Tamayo      Contaduría    17        Samuel Tamayo
12    Paulina  Chavarriaga      Contaduría    17  Paulina Chavarriaga
13     Salome         Mora      Contaduría    19          Salome Mora
14   Santiago      Perdomo  Administración    22     Santiago Perdomo
15  Juan José      Giraldo  Administración    24    Juan José Giraldo